### ISSUE TITLE
Target devices

### ISSUE THREAD

**Issue by paulkramme** [SirWindfield/finance#1]
> I like the UI of VSCode, the sidebar would probably be a nice fit for the project. Selecting different views (overview, charts, settings etc). No plugin system needed here ;) Would just create another vulnerability point within the ecosystem. Theming might be an option (letting the user choose a preferred color scheme).

I think the most important device would be smartphones. Most times, the most important stuff is the inexpensive stuff, like a coffee or a sandwich, which adds up, while you're on route. So my proposal would be that smartphones are targeted. As i enter the work life soon, i have to manage my expenses too, so i would definitely be interested in this program, and be happy to help out. I am currently getting into backend/server programming with Go. I cannot promise anything, but maybe i can help. 

> sync between devices (?)
this would need some serious security stuff to be done right. Open source would be a good approach to minimize backdoors imo.

A server/client model would be best, for the sync as well as for the security, as no critical data would be saved on the devices, but on one place, which is could be better secured such as a database on a server (disk encryption, https, etc...). This would also mean easier data export for data visualization.

**Comment by SirWindfield** [comment]
I have barely any experience with iOS development. I usually code for Android. 

Same goes for server side code. Never actually wrote a server that I then ran 24/7. Never hosted one. Tahnik and me had this idea going and wanted to start with it after devrantron is done and on a stable release branch. 
So tl;dr, I have literally no idea how to start with this project (if I get some time this weekend). :D
So any help is really really appreciated.

**Comment by paulkramme** [comment]
Same for me. Perfect. So we both have much to learn, and will have great benefit no matter which outcome. I am very hyped to start a server project. Lets do it. 
Ive already begun to write server specification. Do you want to do frontend?

**Comment by SirWindfield** [comment]
Sure why not. Js stack would probably make sense to support all platforms. But I have no idea how to use react Native :D I will probably need some time to read up. 
I would love to write an Android app in Java but supporting multiple platforms that way makes it hard. 
I will create an organization later on so we can manage the code bases. 
Any idea for a project name?

**Comment by paulkramme** [comment]
Nope. Id like to write the server in go. Its makes sense, as its well supported, easy to deploy,, and doesnt need much ressources.

**Comment by paulkramme** [comment]
Hm...Trackmon?

**Comment by paulkramme** [comment]
I created [trackmon](https://github.com/trackmon) and invited you. If you have another name, we can change it. 😄

**Comment by tahnik** [comment]
Not coming to any conclusion but I love Google's serverless architecture. In case (just in case :D) the app gets popular, we would not have to worry about scaling the backend. When it comes to syncing real-time data, firebase can help a lot. They have free tiers as well so we would not have to worry about any cost when we are "deving".

Just sharing an opinion.

**Comment by paulkramme** [comment]
This is, IMO, a bad idea, because i couldnt contribute to the project and Go scales very well. If we really want to build a SaaS app, Golang can scale up to 5000 req/min without any performance tuning even if the database to which is written to is on a raspberry pi. DevRant is currently at 6 API requests per second, and i call it successful. If the app becomes that successful firebase is definately a consideration. I have to look into it to learn how it works.

BTW, are you interested in this idea?

**Comment by SirWindfield** [comment]
Will take a look at ReactXP and React Native this weekend. I am not that good at the whole JS stack tbh. So progression probably isn't that fast compared to Android development. 
But sounds like a fun project to get started with mobile dev using the web-stack.
I created a slack group for those that want to join: https://join.slack.com/trackmon/shared_invite/MTc4MDY3MDQxNzQ1LTE0OTM4OTY5MDYtYzVjYzllNDkwZA.

**Comment by tahnik** [comment]
@paulkramme I definitely am. And if I have no problem with either Go or nodeJS :) I will lean a bit towards node just because how beautiful expressJS is :D
